friendly-ssl:
  auto-renew-enabled: false
  acme-session-url: acme://letsencrypt.org/staging
  certificate-key-alias: friendlyssl
  account-private-key-file: account.pem
  keystore-file: keystore.p12
  terms-of-service-file: tos
  order-timeout-seconds: 30
  token-requested-timeout-seconds: 30
  auth-challenge-timeout-seconds: 20
  auto-renewal-hours-before: 72
  error-retry-wait-hours: 1

# In consumer, the following are required to be defined:
#
#  friendly-ssl:
#    domain: domain.com
#    account-email: your@email.com
#
# You will need to change the session url to a production one (default is LetsEncrypt staging):
#
#  friendly-ssl:
#    acme-session-url: acme://letsencrypt.org
#
# To enable manual certificate endpoints, add them to this list
# (don't forget to secure them with proper authentication/authorization):
#
#  friendly-ssl:
#    endpoints-include: certificate, tos
