version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run: mkdir jdk
      - run: curl https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz | tar -xzf - -C jdk --strip-components=1
      - run: realpath ./jdk/bin/java | update-alternatives --set java
      - run: ./mvnw test

workflows:
  version: 2
  Run-Tests:
    jobs:
      - test