version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw package

  test:
    docker:
      - image: openjdk:15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw test
