version: 2.1
machine: true

jobs:
  test:
    docker:
      - image: openjdk:15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw test

workflows:
  version: 2
  Run-Tests:
    jobs:
      - test