name: Release artifact to Maven Central Repository
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Next snapshot version"
        required: true
        default: "X.Y.Z-SNAPSHOT"
jobs:
  release:
    name: Release to Maven Central
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Maven Prepare Release
        run: |
          git config --global user.name 'zrbrown'
          git config --global user.email 'zackrbrown@gmail.com'
          mvn --batch-mode -Dtag=v${{ github.event.inputs.releaseVersion }} release:clean release:prepare -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Maven Release
        run: mvn release:perform
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
